In [1]:
from cutiepy import *
import numpy as np
cutiepy.codegen.DEBUG = True

# $|k\rangle \rightarrow \hat{a}^\dagger|k\rangle$

In [2]:
op = create(5)
y_anon = Ket.anon(5)
cf = generate_cython(evalf(op*y_anon),         
                     func=NDArrayFunction(),            
                     argument_order = [y_anon])

In [3]:
ccf = cf.compiled()

In [4]:
b = basis(5,1)
ccf.pythoncall(numerical(b))

array([[ 0.00000000+0.j],
       [ 0.00000000+0.j],
       [ 1.41421356+0.j],
       [ 0.00000000+0.j],
       [ 0.00000000+0.j]])

# $\rho \rightarrow \left[ \sigma_x, \rho \right]$

In [5]:
op = sigmax()
y_anon = Operator.anon(2)
cf = generate_cython(evalf(Commutator(op, y_anon)),         
                     func=NDArrayFunction(),            
                     argument_order = [y_anon])

In [6]:
ccf = cf.compiled()

In [7]:
ccf.pythoncall(numerical(op))

array([[ 0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j]])

In [8]:
ccf.pythoncall(numerical(sigmay()))

array([[ 0.+2.j,  0.+0.j],
       [ 0.+0.j,  0.-2.j]])

# $\rho \rightarrow -i \left[ \sigma_x, \rho \right]$

In [9]:
op = sigmax()
y_anon = Operator.anon(2)
cf = generate_cython(evalf(-1j*Commutator(op, y_anon)),         
                     func=NDArrayFunction(),            
                     argument_order = [y_anon])

In [10]:
ccf = cf.compiled()

In [11]:
ccf.pythoncall(numerical(sigmay()))

array([[ 2.-0.j,  0.-0.j],
       [ 0.-0.j, -2.+0.j]])